import Phaser from 'phaser';
import { AttackKaiju } from '../entities/AttackKaiju';
import { Core } from '../entities/Core';
import { DEFENSE_KAIJU_STATS, DefenseKaiju, type DefenseKaijuType } from '../entities/DefenseKaiju';
import { AbilitySystem } from '../systems/AbilitySystem';
import { PathSystem } from '../systems/PathSystem';
import { floatingText, formatTime, popImpact } from '../systems/UI';
import { makeAttackSprite, makeDefenseSprite } from '../systems/RenderFactory';

export class DefenseTestScene extends Phaser.Scene {
  private path=new PathSystem(); private core=new Core(); private ability=new AbilitySystem();
  private attackers:AttackKaiju[]=[]; private defenders:DefenseKaiju[]=[]; private av=new Map<string,Phaser.GameObjects.Container>();
  private budget=250; private timer=120000; private selected:DefenseKaijuType='crab'; private kills=0; private dmg=0; private txt!:Phaser.GameObjects.Text; private ghost?:Phaser.GameObjects.Container;
  create(){ this.cameras.main.fadeIn(300); this.draw(); this.cards(); this.txt=this.add.text(20,20,'',{fontSize:'24px'}); this.time.addEvent({delay:2200,loop:true,callback:()=>this.wave()}); this.updateUi(); }
  update(_t:number,d:number){ this.timer-=d; this.ability.tick(this.defenders,d); this.attackers.forEach((a,i)=>this.move(a,d,i)); this.fight(d); this.attackers=this.attackers.filter(a=>a.alive); this.updateUi(); if(!this.core.alive||this.timer<=0) this.end(this.timer>0?false:true); }
  private draw(){ this.cameras.main.setBackgroundColor('#181927'); this.add.rectangle(600,360,1200,720,0x25343f); this.path.mainPath.forEach((p,i,a)=> i&&this.add.line(0,0,a[i-1].x*1.75,a[i-1].y*1.6,p.x*1.75,p.y*1.6,0x7f6040).setLineWidth(40)); this.path.secondaryPath.forEach((p,i,a)=> i&&this.add.line(0,0,a[i-1].x*1.75,a[i-1].y*1.6,p.x*1.75,p.y*1.6,0x4a7547).setLineWidth(30)); this.path.defenseSlots.forEach((p,idx)=>{ const x=p.x*1.75,y=p.y*1.6; this.add.circle(x,y,24,0x2f4550).setStrokeStyle(2,0xcde).setInteractive().on('pointerdown',()=>this.place(idx)); this.add.circle(x,y,26,0x99ddff,0.05); }); const c1=this.add.circle(1060,360,42,0xf15b7f); this.tweens.add({targets:c1,scale:1.08,yoyo:true,duration:600,repeat:-1}); this.input.on('pointermove',(p:Phaser.Input.Pointer)=>this.preview(p)); }
  private cards(){ let x=220; (Object.keys(DEFENSE_KAIJU_STATS) as DefenseKaijuType[]).forEach(k=>{ const s=DEFENSE_KAIJU_STATS[k]; const card=this.add.rectangle(x,660,220,92,0x263a61).setStrokeStyle(2,0x8bf2ff).setInteractive(); this.add.text(x-90,625,k,{fontSize:'18px'}); this.add.text(x-90,650,`Coût:${s.cost}`,{fontSize:'15px'}); makeDefenseSprite(this,k,x+70,652).setScale(0.55); card.on('pointerdown',()=>{this.selected=k;}); x+=240;}); this.input.keyboard?.on('keydown-SPACE',()=>{ const d=this.defenders[0]; if(!d)return; floatingText(this,d.x,d.y-30,this.ability.activate(d,this.attackers),'#8bf2ff');}); }
  private preview(p:Phaser.Input.Pointer){ this.ghost?.destroy(); this.ghost=makeDefenseSprite(this,this.selected,p.x,p.y).setAlpha(0.35); const valid=this.path.defenseSlots.some(s=>Math.hypot(s.x*1.75-p.x,s.y*1.6-p.y)<24)&&!this.defenders.some(d=>Math.hypot(d.x-p.x,d.y-p.y)<24); this.ghost.iterate((x:any)=>x.setTint?.(valid?0x66ff66:0xff6666)); }
  private place(slot:number){ const p=this.path.defenseSlots[slot]; const x=p.x*1.75,y=p.y*1.6; if(this.defenders.some(d=>d.x===x&&d.y===y))return; const c=DEFENSE_KAIJU_STATS[this.selected].cost; if(this.budget<c) return; this.budget-=c; const d=new DefenseKaiju(`d${slot}${Date.now()}`,this.selected,x,y); this.defenders.push(d); makeDefenseSprite(this,this.selected,x,y); }
  private wave(){ const kind=(['breaker','sprinter','tank','acid'] as const)[Math.floor(Math.random()*4)]; const a=new AttackKaiju(`w${Date.now()}`,kind,100,360); this.attackers.push(a); this.av.set(a.id,makeAttackSprite(this,a.x,a.y,0xffc857)); }
  private move(a:AttackKaiju,d:number,i:number){ const path=this.path.choosePath(i).map(p=>({x:p.x*1.75,y:p.y*1.6})); const t=path[Math.min(a.targetPointIndex,path.length-1)]; const s=(a.stats.speed*a.slowFactor)*d/1000*1.2; const di=Math.hypot(t.x-a.x,t.y-a.y); if(di<=s){a.x=t.x;a.y=t.y;a.targetPointIndex++; if(a.targetPointIndex>=path.length){this.core.damage(a.stats.damage);this.dmg+=a.stats.damage; this.cameras.main.shake(90,0.003); a.alive=false; this.av.get(a.id)?.destroy();}} else {a.x+=(t.x-a.x)/di*s;a.y+=(t.y-a.y)/di*s;} this.av.get(a.id)?.setPosition(a.x,a.y); }
  private fight(delta:number){ this.defenders.forEach(d=>{ d.tick(delta); if(d.attackCooldown>0)return; const t=this.attackers.find(a=>a.alive&&Math.hypot(a.x-d.x,a.y-d.y)<=d.stats.range*1.5); if(!t)return; if(d.kaijuType==='laser'){ this.add.line(0,0,d.x,d.y,t.x,t.y,0xff00ff).setLineWidth(3).setAlpha(0.8); }
    if(d.kaijuType==='blob'){ this.add.circle(d.x,d.y,70,0x57cc3f,0.08); t.applySlow(0.65,1500);} if(d.kaijuType==='nest' && Math.random()>0.6){ this.add.circle(d.x+Phaser.Math.Between(-14,14),d.y+20,4,0xfbe09c); }
    t.takeDamage(d.stats.damage); popImpact(this,t.x,t.y); floatingText(this,t.x,t.y,`-${d.stats.damage}`); d.attackCooldown=850; if(!t.alive){this.kills++; this.av.get(t.id)?.destroy(); for(let i=0;i<8;i++){ const c=this.add.circle(t.x,t.y,3,0xffc857); this.tweens.add({targets:c,x:t.x+Phaser.Math.Between(-20,20),y:t.y+Phaser.Math.Between(-20,20),alpha:0,duration:220,onComplete:()=>c.destroy()}); }} }); }
  private updateUi(){ this.txt.setText(`DEFENSE TEST Budget:${this.budget} Cœur:${this.core.hp}/1000 Temps:${formatTime(this.timer)} Dégâts:${this.dmg}`); }
  private end(win:boolean){ this.scene.start('CollectionScene',{ end:true, win, coreDamage:this.dmg, kills:this.kills, adn:Math.floor(this.kills*6+(win?120:25)), from:'Defense' }); }
}
